### PR TITLE
fix: Onboarding next button event, signup and login design fix

### PR DESCRIPTION
**Pull request by DesmondTambe**
## Description

- Onboarding next screen onPress event handler for onboarding slide animation
- Login design fixes ( ColorScheme, spacing around widget, on-page screen event)
- Signup fixes relative to Figma design

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read and ran all relevant commands as specififed in the Running Tests section of the [Contributor Guide].
- [ ] The title of the PR follows the [Conventional Commits] guideline
- [ ] My local branch follows the naming standards in the [Deepsource Branch Naming Convention] or [Biodiversity Branch Naming Convention]
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy],
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

[Contributor Guide]: https://github.com/FlutterPlaza/.github/blob/main/CONTRIBUTING.md
[Conventional Commits]: https://www.conventionalcommits.org/en/v1.0.0-beta.4/
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[Biodiversity Branch Naming Convention]: https://bit.ly/3DyYSwM
[Deepsource Branch Naming Convention]: https://bit.ly/3Y08Gs4

### CODE REVIEW

**Comment by jeffrey0606** [comment]
You bro please also resolve this one so I can merge it

**Review by jeffrey0606 — CHANGES_REQUESTED** [review]
Hello @DesmondTambe the background color on this TabBar is missing, you can check the figma design.

Screenshot 2023-03-27 at 18 23 54

**Comment by DesmondTambe** [comment]
Screenshot_20230327-183948

Yoo @jeffrey0606

**Comment by jeffrey0606** [comment]
Sorry 😅 @DesmondTambe forgot to switch branch on my end 🥲

**Review by jeffrey0606 — APPROVED** [review]

**Pull request merged**
