### PR TITLE
feat: Added App Icon with Flavor for Android and iOS #39

### PR DESCRIPTION
**Pull request by fonkamloic**
## Description

A proposed solution for Issue #39  

- [ x] Created different app icons for each flavor for each platform 
- [ x]  Updated the app icons in the appropriate folders for both Android and iOS
- [ x]  Verify that the correct app icon is displayed for each flavor on both Android and iOS
- [ x]  Make sure that the app icons meet the current design standards of Google and Apple

**Changes**

- [x ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Review by lkmandy — CHANGES_REQUESTED** [review]
Please consider revising your commit messages, I noticed some minor errors

[feat: app ios app icon flavors for ios]
-  Here I believe it should be `"add"` instead of `"app"`

[feat: apped icon flavors for android]
- Did you mean `"added"` instead of `"apped"`?

[style: fixed format and analysers issues]
- Given we have just one dart `analyser`, let's keep `analyser `singular

Every other thing looks fine.
Thank you for your contribution

**Comment by fonkamloic** [comment]
Unfortunately, I know of no method to check a commit hash message. 
So I pay more attention to the next commit message.

**Comment by lkmandy** [comment]
>  You can use `git rebase -i  HEAD~n` and go back to n number of commits and only edit the commit messages by replacing `pick` with `reword` for each commit you wish to edit.

if this is something you consider a soft requirement, then we can adopt that.

**Review by lkmandy — COMMENTED** [review]
You can use `git rebase -i  HEAD~n` and go back to n number of commits and only edit the commit messages by replacing `pick ` with `reword` for each commit you wish to edit.

if this is something you consider a soft requirement, then we can adopt that.

**Review by lkmandy — APPROVED** [review]

**Comment by fonkamloic** [comment]
fix #39

**Pull request merged**
