### PR TITLE
fix: Dependency updates

### PR DESCRIPTION
**Pull request by TikuGaelle**
## Description

*The analysis_options.yaml file has an updated line `sort_pub_dependencies: false` 
which resolves the sort pub dependencies error.
* The pubspec.lock file has updated dependency versions 

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read and ran all relevant commands as specififed in the Running Tests section of the [Contributor Guide].
- [x] The title of the PR follows the [Conventional Commits] guideline
- [x] My local branch follows the naming standards in the [Deepsource Branch Naming Convention] or [Biodiversity Branch Naming Convention]
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy],
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

[Contributor Guide]: https://github.com/FlutterPlaza/.github/blob/main/CONTRIBUTING.md
[Conventional Commits]: https://www.conventionalcommits.org/en/v1.0.0-beta.4/
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[Biodiversity Branch Naming Convention]: https://bit.ly/3DyYSwM
[Deepsource Branch Naming Convention]: https://bit.ly/3Y08Gs4

### CODE REVIEW

**Comment by lkmandy** [comment]
@TikuGaelle I noticed you merge previous branches that represent separate PRs into a new PR with its own changes.
Is there a reason for this?

I believe the normal standard is to make single changes or groups of related changes per PR.
If you need input from another PR, you just need to wait until it's approved and merged.

The issue with your style of merging is that you already submitted a PR that is under review, and now you take that PR
merge it into another PR which is like a duplicate.

**Comment by TikuGaelle** [comment]
> @TikuGaelle I noticed you merge previous branches that represent separate PRs into a new PR with its own changes. Is there a reason for this?
> 
> I believe the normal standard is to make single changes or groups of related changes per PR. If you need input from another PR, you just need to wait until it's approved and merged.
> 
> The issue with your style of merging is that you already submitted a PR that is under review, and now you take that PR merge it into another PR which is like a duplicate.

Hi Amanda. 
I do not merge the branches on purpose, i think they are merged because the previous PRs are still open when the new PR comes in... 
If you know of any way i can stop the merges, please let me know. Thanks.

**Comment by fonkamloic** [comment]
To solve this issue, 

1. we need to merge pull requests in order (ascending). 
2. @lkmandy Please correct me if I am wrong but @TikuGaelle has not merged any PR or should not merge any PR.
3. @TikuGaelle has to complete one pull request review and solve before moving to another. 
4. @TikuGaelle Make your pull the request title to reflect the changes made in the code. I saw some pull requests will very confusing titles. For instance, this PR right now has nothing to do with dependency updates. I don't see why dependency you are updating. 

You don't need to update pubspec.lock. it is a generated file. You can even delete it.

**Comment by lkmandy** [comment]
@fonkamloic 
- **point 2:**  Oh no Brenda doesn't have permission to and hasn't done so, just you has that permission
- I meant for example I submit PR1, then locally I merge PR1's local branch into another new local branch that contains different changes and then submit PR2. So PR1 is a subset of PR2. You can see the same changes from PR1 in PR2 + the new ones. I think this makes the PRs duplicate.

**Comment by fonkamloic** [comment]
```
Description says:

*The analysis_options.yaml file has an updated line sort_pub_dependencies: false
which resolves the sort pub dependencies error.

The pubspec.lock file has updated dependency versions
```


We don't want to do any of the things mentioned here. pubspec.lock should be deleted 
and pubspec.yaml should stay ordered. 

closing PR...

**Comment by fonkamloic** [comment]
The PR was supposed to be called "Missing Assets" 

@TikuGaelle Please let your message reflect your changes

**Pull request merged**
