### PR TITLE
chore: Sign up internationalization

### PR DESCRIPTION
**Pull request by TikuGaelle**
## Description

* Internationalization of sign up page in both french and English. Solving issue #17 
* Change of Log in and sign in titles to "Login Wtih" and "Register With" respectively
* Deleted repeated strings in app_en.arb and app_fr.arb files

 
 
  

 

 
## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [x] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [x] 🗑️ Chore

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read and ran all relevant commands as specififed in the Running Tests section of the [Contributor Guide].
- [ ] The title of the PR follows the [Conventional Commits] guideline
- [ ] My local branch follows the naming standards in the [Deepsource Branch Naming Convention] or [Biodiversity Branch Naming Convention]
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy],
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

[Contributor Guide]: https://github.com/FlutterPlaza/.github/blob/main/CONTRIBUTING.md
[Conventional Commits]: https://www.conventionalcommits.org/en/v1.0.0-beta.4/
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[Biodiversity Branch Naming Convention]: https://bit.ly/3DyYSwM
[Deepsource Branch Naming Convention]: https://bit.ly/3Y08Gs4

### CODE REVIEW

**Review by lkmandy — CHANGES_REQUESTED** [review]
1. I think we should keep the signup and login simple to avoid distorted UIs in different languages. Plus it's always a win when following the KISS principle.
Here are my suggestions

```
Login With                                          Connexion avec
Email   |   Phone Number                            Email  |   Numéro or Téléphone
```

```
Register WIth                                       S'inscrire avec
Email   |   Phone Number                            Email      |    Numéro or Téléphone
```
_I think someone whose French is better can improve these suggestions._

2. Please add both French and English demo images to this PR
Give your images a height and a width using  ``   to avoid very large images

**Comment by TikuGaelle** [comment]
> 1. I think we should keep the signup and login simple to avoid distorted UIs in different languages as much as possible
>    Here are my suggestions
> 
> ```
> Login With
> Email   |   Phone Number
> ```
> 
> ```
> Register WIth
> Email   |   Phone Number
> ```
> 
> 2. Please add both French and English demo images to this PR
>    Give your images a height and a width using  ``   to avoid very large images

Okay Amanda. Thanks. 
For the change in UI, let's hear what @fonkamloic  has to say

**Comment by fonkamloic** [comment]
When looking for a translation of a string for internalization, it is important to search for the shortest translation that still preserves the meaning. Any translation that breaks the UI will not be accepted.

**Review by fonkamloic — CHANGES_REQUESTED** [review]
I agree with everything Amanda said. 


Also, why is the bottom of your screen on the screenshot black?

**Comment by TikuGaelle** [comment]
> I agree with everything Amanda said.
> 
> Also, why is the bottom of your screen on the screenshot black?

I think that's my phone, not the UI...

**Review by fonkamloic — APPROVED** [review]

**Pull request merged**
